name: CI

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build-and-test:
    name: Build and Test Go Echo Service
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      # Step 4: Lint the Go code using golangci-lint
      - name: Run linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      # Step 5: Build the project
      - name: Build the Go Echo project
        run: |
          go build -o docker-api
